- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Remove old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: ownload and extract frontend content
  include_role:
    name: common
    tasks_from: download.yml

- name: Copy the extracted content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy the roboshop.conf file from controle node to front end server
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Restart service Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes





