- name: Install Redis repo
  ansible.builtin.yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install redis
  ansible.builtin.yum:
    name: redis
    enablerepo: remi
    state: present

- name: change listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis service
  systemd:
    name: redis
    enabled: yes
    state: started
