- name: Add RoboShop Application User
  ansible.builtin.user:
    name: roboshop
  register: app_user

- name: Download from Github
  include_tasks:
    file: download-from-github.yml

- name: Delete Old App code
  file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Copy the extracted content
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop
    group: roboshop