- name: install NodeJs
  ansible.builtin.yum:
    name: ["nodejs", "make", "gcc-c++"]
    state: present

- name: Add the roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Include task list in play
  include_tasks:
    file: download.yml

- name: Copy the extracted content
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Update packages based on package.json to their latest version.
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}/
    state: present
  become_user: roboshop

- name: Copy the systemd file
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start Mongodb Service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes
    daemon_reload: yes





