- name: install NodeJs
  ansible.builtin.yum:
    name: ["nodejs", "make", "gcc-c++"]
    state: present

- name: Add the roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Include task list in play
  include_tasks:
    file: download.yml

- name: Copy the extracted content
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes


