- name: Install Python
  yum:
    name: ["python36", "gcc", "python3-devel"]
    state: present

- name: Add roboshop application user
  ansible.builtin.user:
    name: roboshop
  register: app_user

- name: Download GitHub
  include_tasks:
    file: download.yml

- name: Delete Old App Code
  file:
     path: /home/roboshop/{{COMPONENT}}
     state: absent

- name: Copy the extracted content
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Running mvn clean
  shell: "mvn clean package" && mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}

- name: Update SystemD Configuration
  copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

#- name: print app_user info
#  debug:
#    msg: {{app_user}}

- name: modify uid in paymemt.ini
  lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: "^uid"
    line: "uid = {{app_user.uid}}"

- name: modify gid in paymemt.ini
  lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: "^gid"
    line: "gid = {{app_user.group}}"

- name: Restart {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

