pipeline {
  agent {
    node { label 'Agent1'}
  }
  environment {
    SSH = credentials('Terraform')
  }
  options {
    ansiColor('xterm')
  }

  parameters {
    choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick a terraform action')
  }

  stages {
    stage('one') {
      steps {
        echo "${SSH_USR}"
        echo "${SSH_PSW}"
      }
    }

    stage('Terraform INIT') {
      steps {
        sh 'cd  Terraform/Roboshop-project; ls ; terraform init'
      }
    }

    stage('Terraform Apply') {
      when {
        environment name: 'ACTION', value: 'apply'
      }
      steps {
        sh '''
          cd Terraform/Roboshop-project
          ls
          terraform apply -auto-approve
        '''
      }
    }

    stage('Terraform Destroy') {
      when {
        environment name: 'ACTION', value: 'destroy'
      }
      steps {
        sh '''
          cd Terraform/Roboshop-project
          ls
          terraform destroy -auto-approve
        '''
      }
    }

  }
}