- name: Demo on tags task
  hosts: localhost
  tasks:
    - name: Print Ubuntu
      debug:
        msg: Ubuntu
      tags:
        - ubuntu
        - redhat
    - name: Print Centod
        debug:
          msg: Centos
        tags:
          - centos
          - redhat
