- name: Demo on tags task
  hosts: localhost
  tasks:
    - name: Print Ubuntu
      debug:
        msg: Ubuntu
      tags:
        - ubuntu
        - redhat
    - name: Print Centos
      debug:
        msg: Centos
      tags:
        - centos
        - redhat
        -
- name: Ubuntu task
  hosts: localhost
  tags:
    - ubuntu
  tasks:
    - name: Print Ubuntu
      debug:
        msg: Ubuntu task

- name: Centos task
  hosts: localhost
  tags:
    - centos
  tasks:
    - name: Print Centos
      debug:
        msg: centos task

