- name: roboshop frontend project
  hosts: FRONTEND
  tags:
    - frontend
  become: yes
  roles:
    - name: frontend

- name: roboshop frontend project
  hosts: MONGODB
  tags:
    - mongodb
  become: yes
  roles:
    - name: mongodb



