- name: roboshop frontend project
  hosts: FRONTEND
  become: yes
  tags: frontend
  roles:
    - name: frontend

- name: roboshop frontend project
  hosts: MONGODB
  become: yes
  tags: mongodb
  roles:
    - name: mongodb

- name: roboshop frontend project
  hosts: CATALOGUE
  become: yes
  tags: catalogue
  roles:
    - name: catalogue

- name: roboshop redis project
  hosts: REDIS
  become: yes
  tags: redis
  roles:
    - name: redis

- name: roboshop user project
  hosts: USER
  become: yes
  tags: user
  roles:
    - name: user

- name: roboshop cart project
  hosts: CART
  become: yes
  tags: cart
  roles:
    - name: cart

- name: roboshop MYSQL project
  hosts: MYSQL
  become: yes
  tags: mysql
  roles:
    - name: mysql

- name: roboshop SHIPPING project
  hosts: SHIPPING
  become: yes
  tags: shipping
  roles:
    - name: shipping



