- name: Setup Mysql Repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install mysql server
  ansible.builtin.yum:
    name: mysql-community-server
    state: present

- name: start mysql server
  ansible.builtin.systemd:
    name: mysqld
    enabled: yes
    state: started

- name: Check the default password
  shell: echo "show databases;" | mysql -uroot -pRoboShop@1
  register: default_mysql_check
  ignore_errors: yes

- name: print
  debug:
    msg: "{{default_mysql_check}}

- name: Grab default Password
  shell: grep 'A temporary password' /var/log/mysqld.log  | awk '{print $NF}'
  register: out




