// pipeline {
//   agent {
//     node { label 'Agent1'}
//   }
//
//   stages {
//     stage('one') {
//       steps {
//         sh 'echo hello ; echo hey'
//       }
//     }
//   }
// }

pipeline {
  agent all

  stages {
    stage('JAVA node') {
      agent {
        label 'JAVA'
      }
    steps {
      sh 'echo hello'
    }
  }
    stage('NODEJS node') {
      agent {
        label 'NODEJS'
      }
      steps {
        sh 'echo hey'
      }
    }
  }
}