// pipeline {
//   agent {
//     node { label 'Agent1'}
//   }
//
//   stages {
//     stage('one') {
//       steps {
//         sh 'echo hello ; echo hey'
//       }
//     }
//   }
// }



// pipeline {
//   agent any
//
//   stages {
//     stage('JAVA node') {
//       agent {
//         label 'JAVA'
//       }
//     steps {
//       sh 'echo hello'
//     }
//   }
//     stage('NODEJS node') {
//       agent {
//         label 'NODEJS'
//       }
//       steps {
//         sh 'echo hey'
//       }
//       post {
//         always {
//           sh ' echo NODEJS'
//         }
//       }
//     }
//   }
//   post {
//
//     always {
//      sh 'echo master'
//     }
//   }
// }


pipeline {
  agent any
  enivironment{
    DEMO_URL = "google.com"
  }
  stages {
    stage('one') {
      enivironment{
        DEMO_URL = "yahoo.com"
      }
      steps {
        sh 'echo ${DEMO_URL}'
      }
    }
  }
}