- name: Demo on Variabls
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: print a variable
      debug:
        msg: "URL = {{URL}}"

    - name: print task level
      vars:
        URL: task.google.com
      debug:
        msg: "URL = {{URL}}"


