frontend:
	@echo Installing frontend
cart:
	@echo Installing cart
catalouge:
	@echo Installing catalouge
mongodb:
	@echo Installing mongodb
mysql:
	@echo Installing mysql
payment:
	@echo Installing payment
rabbitmq:
	@echo Installing rabbitmq
redis:
	@echo Installing redis
shipping:
	@echo Installing shipping
user:
	@echo Installing user


