help:			## Print this message
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend:		## Install frontend component
	@echo Installing frontend
cart:			## Install frontend component
	@echo Installing cart
catalouge:		## Install catalouge component
	@echo Installing catalouge
mongodb:		## Install mongodb component
	@echo Installing mongodb
mysql:			## Install mysql component
	@echo Installing mysql
payment:		## Install payment component
	@echo Installing payment
rabbitmq:		## Install rabbitmq component
	@echo Installing rabbitmq
redis:			## Install radis component
	@echo Installing redis
shipping:		## Install shipping component
	@echo Installing shipping
user:			## Install user component
	@echo Installing user
databases:		mongodb redis mysql rabbitmq	## Install All databases

